### ISSUE TITLE
deprecation warnings with ember 2.12

### ISSUE THREAD

**Issue by olivierchatry** [knownasilya/ember-cli-deploy-gcloud-storage#7]
DEPRECATION: `ember-cli/ext/promise` is deprecated, use `rsvp` instead. Required here:
  Object.<anonymous> (C:\Users\olivier\Documents\fieldap\node_modules\ember-cli-deploy-gcloud-storage\index.js:6:15)
DEPRECATION: `ember-cli/ext/promise` is deprecated, use `rsvp` instead. Required here:
  Object.<anonymous> (C:\Users\olivier\Documents\fieldap\node_modules\ember-cli-deploy-gcloud-storage\libs\upload.js:3:15)

**Comment by knownasilya** [comment]
Released as v0.2.0
