### ISSUE TITLE
projectId does not seem to work in the deploy config

### ISSUE THREAD

**Issue by mansona** [knownasilya/ember-cli-deploy-gcloud-storage#9]
Howdy folks 👋 

I've just tried to specify the projectId using the ENV in deploy.js: 

```
    ENV['gcloud-storage'] = {
      projectId: 'super-awesome-project',
      bucket: 'best-bucket'
    };
```
but this doesn't work. I needed to do it on command line like this: `GCLOUD_PROJECT=super-awesome-project ember deploy production`

**Comment by knownasilya** [comment]
Looks like it's due to the fact that you didn't specify `credentials`, see https://github.com/knownasilya/ember-cli-deploy-gcloud-storage/blob/master/index.js#L50

**Comment by mansona** [comment]
@knownasilya I wanted it to use the global credentials from the installed gcloud cli 🤔 

I think I'll submit a PR that allows them to be specified independently

**Comment by knownasilya** [comment]
Sounds good 👍

**Comment by knownasilya** [comment]
New version v0.2.1 published.
